global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'video-service'
    static_configs:
      - targets: ['host.docker.internal:50051']

  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:50052']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:5000']
